/* See LICENSE file for copyright and license details. */
/* smb — generating and installing the Samba configuration */

#ifndef GRAPH_SMB_H
#define GRAPH_SMB_H

#include <limits.h>
#include <stddef.h>

/* Graph assumes exclusive ownership of Samba on the serving machine (PLAN
 * §9.4). It generates this file whole and never merges with what is there. */
#define SMB_CONF "/etc/samba/smb.conf"

/* The configuration in place before Graph first ran is preserved here once,
 * and never overwritten by a later run (§9.5). Removing it returns Graph to
 * first-run behaviour. */
#define SMB_CONF_PRESERVED "/etc/samba/smb.conf.pre-graph"

/* Upper bound on a generated configuration. Ample for SMB_MAX_SHARES
 * shares; generation fails rather than truncating if it is ever exceeded. */
#define SMB_TEXT_MAX   65536

#define SMB_MAX_ADDRS  16
#define SMB_MAX_SHARES 64
#define SMB_NAME_MAX   64
#define SMB_USER_MAX   64

/* Addresses are carried as text. Graph does not need to understand what
 * network an address belongs to (§9.3), so it never parses them. */
#define SMB_ADDR_MAX   64

/* Asking for this address is asking to be served on every interface, public
 * ones included. Samba cannot bind it, so graph expresses the request by
 * lifting `bind interfaces only` instead. */
#define SMB_ADDR_EVERY "0.0.0.0"

struct smb_share {
	char name[SMB_NAME_MAX];
	char path[PATH_MAX];
	char user[SMB_USER_MAX];	/* empty when no user was given */
};

/* The whole of what Graph puts in the configuration. Held in memory only for
 * as long as it takes to regenerate; the file remains the definition (§11). */
struct smb_conf {
	char addrs[SMB_MAX_ADDRS][SMB_ADDR_MAX];
	size_t naddrs;
	struct smb_share shares[SMB_MAX_SHARES];
	size_t nshares;
};

/* Result of installing a generated configuration. */
enum smb_write {
	SMB_WRITE_UNCHANGED,	/* identical to what is already there */
	SMB_WRITE_UPDATED,	/* replaced a configuration Graph had written */
	SMB_WRITE_DISPLACED,	/* replaced one Graph had not; original preserved */
};

/* The header identifying a configuration graph generated. Read-back trusts
 * only a file carrying it: a configuration graph did not write may define
 * shares that are not Graph repositories, and carrying those forward would
 * put them back in a file that must serve repositories and nothing else
 * (§9.6). This records provenance, not state, so §11 is unaffected. */
#define SMB_HEADER "# Generated by graph."

/* Recover what graph last wrote, so that regenerating does not drop shares or
 * addresses an earlier command established. Returns 1 if a graph-generated
 * configuration was read, 0 if there is none to carry forward, -1 on error. */
int smb_read(struct smb_conf *conf);

/* Whether a share or user name is one graph will accept. Names reach the
 * configuration file and the Samba commands graph runs, so they are held to a
 * conservative set rather than quoted and hoped for. */
int smb_name_ok(const char *s);

/* Whether an address is free of anything that could be read as an option or
 * a shell fragment. Graph does not otherwise interpret addresses (§9.3). */
int smb_addr_ok(const char *s);

/* Run a command with no shell involved. Returns its exit status, or -1. */
int smb_run(char *const argv[]);

/* Whether addr is an address of this machine. Returns 1 if it is, 0 if not,
 * -1 if this machine's addresses could not be read. SMB_ADDR_EVERY always
 * answers 1: it is a request, not an address to find. */
int smb_local_address(const char *addr);

/* Writes this machine's addresses into dst as a comma-separated list, so a
 * refusal can say what was available instead. Returns 0, or -1. */
int smb_addresses(char *dst, size_t size);

/* Whether conf asks to be served on every interface rather than on named
 * addresses. */
int smb_every_interface(const struct smb_conf *conf);

/* Render conf into a buffer. Returns 0, or -1 if it would not fit. */
int smb_generate(const struct smb_conf *conf, char *dst, size_t size);

/* Run the generated configuration past testparm. Returns 1 if Samba would
 * accept it, 0 if not, -1 if testparm could not be run at all. */
int smb_validate(const char *text);

/* Install text as the Samba configuration, following §9.5: preserve a
 * pre-Graph original once, skip an identical write, and never install a
 * configuration testparm rejects. Returns an enum smb_write, or -1. */
int smb_install(const char *text, enum smb_write *how);

/* Restart the SMB service, which §9.5 requires only when the configuration
 * actually changed: changing the listening address needs a restart rather
 * than a reload, and a restart drops connections clients may be using.
 * Returns 0 on success, -1 if the service could not be restarted. */
int smb_restart(void);

/* Whether the SMB service is currently running. Reports 0 both when it is
 * stopped and when there is no service manager to ask, so it answers "is it
 * serving" rather than "why not". */
int smb_running(void);

/* Start the SMB service if it is not already running. Idempotent, so it can
 * be asked for whenever something should be served -- notably when the
 * configuration already describes a share but the service is down, as it is
 * after a reboot with the unit disabled. Returns 0, or -1. */
int smb_start(void);

/* Stop the SMB service, for when no repository remains to serve. Returns 0,
 * or -1 if the service could not be stopped. */
int smb_stop(void);

/* Whether this is a platform where graph configures Samba. config and serve
 * are Linux-only: macOS runs its own SMB implementation, so the model in
 * §9 does not apply there (§13). */
int smb_on_linux(void);

/* Checks that this machine can be configured at all: the right platform,
 * Samba installed, and the privileges to configure it. Reports what is wrong
 * and returns -1 rather than escalating or installing anything (§8). */
int smb_preconditions(const char *cmd);

/* Reports a displaced configuration. A notice, not a prompt (§9.4). */
void smb_report(enum smb_write how);

/* Whether the VFS modules the generated shares depend on are installed.
 * Returns 1 if all are present, 0 if any is missing (naming them in missing),
 * -1 if smbd could not be asked. A missing module is not a configuration
 * error Samba will report: the share parses, is listed, and then refuses
 * every connection, so graph checks before serving rather than after. */
int smb_vfs_modules(char *missing, size_t size);

/* Whether Samba already knows this user. Samba stays the authority for SMB
 * users; graph keeps no record of its own (§10). */
int smb_user_exists(const char *user);

/* Create a Samba user with the given password. Returns 0, or -1. */
int smb_user_create(const char *user, const char *password);

/* Whether Samba is installed at all. `serve` fails with instructions rather
 * than installing anything itself (§8). */
int smb_present(void);

#endif /* GRAPH_SMB_H */
