/* See LICENSE file for copyright and license details. */
/* smb — generating and installing the Samba configuration */

#include <arpa/inet.h>
#include <errno.h>
#include <ifaddrs.h>
#include <netinet/in.h>
#include <stdarg.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>

#include "graph.h"
#include "smb.h"

/* Appends to dst, tracking overflow in one place so the caller can check once
 * at the end rather than after every field. */
struct buf {
	char *p;
	size_t size;
	size_t len;
	int overflow;
};

static void
bufcat(struct buf *b, const char *fmt, ...)
{
	va_list ap;
	int n;

	if (b->overflow)
		return;
	va_start(ap, fmt);
	n = vsnprintf(b->p + b->len, b->size - b->len, fmt, ap);
	va_end(ap);
	if (n < 0 || (size_t)n >= b->size - b->len) {
		b->overflow = 1;
		return;
	}
	b->len += (size_t)n;
}

/* Whether the configuration asks to be served on every interface (Â§9.3). */
int
smb_every_interface(const struct smb_conf *conf)
{
	size_t i;

	for (i = 0; i < conf->naddrs; i++)
		if (!strcmp(conf->addrs[i], SMB_ADDR_EVERY))
			return 1;
	return 0;
}

int
smb_generate(const struct smb_conf *conf, char *dst, size_t size)
{
	struct buf b;
	size_t i;

	if (size == 0)
		return -1;
	b.p = dst;
	b.size = size;
	b.len = 0;
	b.overflow = 0;
	dst[0] = '\0';

	bufcat(&b,
	    "# Generated by graph. Do not edit.\n"
	    "#\n"
	    "# graph owns this file and rewrites it whole on every change. Any\n"
	    "# edit made here is lost the next time graph runs.\n"
	    "\n"
	    "[global]\n");

	/* The address is never defaulted. Samba's own default is to listen
	 * on every interface, and exposure must always be an explicit decision
	 * (§8), so a configuration with no address is not generated at all. */
	bufcat(&b, "\tinterfaces =");
	for (i = 0; i < conf->naddrs; i++)
		bufcat(&b, " %s", conf->addrs[i]);

	/* 0.0.0.0 is taken as a deliberate request to serve on every
	 * interface. Samba cannot bind that address, so what expresses the
	 * request is lifting the restriction rather than the address itself;
	 * the address stays in the file so that reading it back recovers what
	 * was asked for. Naming addresses leaves the restriction in place, so
	 * a repository is never offered somewhere it was not asked to be. */
	bufcat(&b, "\n\tbind interfaces only = %s\n",
	    smb_every_interface(conf) ? "no" : "yes");

	/* §9.6: Graph repositories and nothing else. */
	bufcat(&b,
	    "\tserver min protocol = SMB2\n"
	    "\tmap to guest = never\n"
	    "\tload printers = no\n"
	    "\tprintcap name = /dev/null\n"
	    "\tdisable spoolss = yes\n"
	    "\tshow add printer wizard = no\n"
	    "\tusershare max shares = 0\n"
	    "\tunix extensions = no\n");

	/* macOS keeps Finder metadata and resource forks in extended
	 * attributes. With nowhere to put them it writes an AppleDouble
	 * "._name" file beside every file it touches, which would leave the
	 * repository half full of entries that mean nothing to anything else. */
	bufcat(&b, "\tea support = yes\n");

	for (i = 0; i < conf->nshares; i++) {
		const struct smb_share *s = &conf->shares[i];

		bufcat(&b, "\n[%s]\n", s->name);
		bufcat(&b, "\tpath = %s\n", s->path);
		bufcat(&b,
		    "\tbrowseable = yes\n"
		    "\tread only = no\n"
		    "\tguest ok = no\n");
		/* Each share is confined to the repository it exposes: a
		 * symlink inside must not become a path out of it (§9.6). */
		bufcat(&b,
		    "\tfollow symlinks = no\n"
		    "\twide links = no\n");
		/* Store the macOS metadata in the attribute rather than beside
		 * the file. fruit must come before streams_xattr; it is the
		 * module that reads the attribute the other one provides. */
		bufcat(&b,
		    "\tvfs objects = fruit streams_xattr\n"
		    "\tfruit:metadata = stream\n");
		if (s->user[0])
			bufcat(&b, "\tvalid users = %s\n", s->user);
	}

	return b.overflow ? -1 : 0;
}

/* Write text to a file created with mkstemp under dir. Returns a malloc'd
 * path the caller unlinks and frees, or NULL. */
static char *
write_temp(const char *dir, const char *text)
{
	char *path;
	size_t len;
	int fd;
	ssize_t n;

	len = strlen(dir) + sizeof("/.graph.XXXXXX");
	if (!(path = malloc(len)))
		return NULL;
	snprintf(path, len, "%s/.graph.XXXXXX", dir);
	if ((fd = mkstemp(path)) < 0) {
		free(path);
		return NULL;
	}
	len = strlen(text);
	n = write(fd, text, len);
	if (n < 0 || (size_t)n != len || close(fd) < 0) {
		unlink(path);
		free(path);
		return NULL;
	}
	return path;
}

int
smb_validate(const char *text)
{
	char cmd[PATH_MAX + 64];
	char *tmp;
	int rc;

	/* testparm reads a file, so the candidate is written to one first. It
	 * goes beside the real configuration so that a validated file and the
	 * installed one differ only in name. */
	if (!(tmp = write_temp("/etc/samba", text)))
		return -1;

	/* Only the exit status is used. testparm's normalized output varies
	 * between Samba versions; its exit status does not. */
	snprintf(cmd, sizeof(cmd), "testparm -s '%s' >/dev/null 2>&1", tmp);
	rc = system(cmd);

	unlink(tmp);
	free(tmp);

	if (rc == -1)
		return -1;
	return rc == 0 ? 1 : 0;
}

int
smb_present(void)
{
	return system("command -v smbd >/dev/null 2>&1") == 0;
}

/* Reads path into a malloc'd NUL-terminated buffer, or NULL. */
static char *
read_file(const char *path)
{
	FILE *f;
	char *buf;
	long size;
	size_t got;

	if (!(f = fopen(path, "rb")))
		return NULL;
	if (fseek(f, 0, SEEK_END) < 0 || (size = ftell(f)) < 0 ||
	    fseek(f, 0, SEEK_SET) < 0) {
		fclose(f);
		return NULL;
	}
	if (!(buf = malloc((size_t)size + 1))) {
		fclose(f);
		return NULL;
	}
	got = fread(buf, 1, (size_t)size, f);
	fclose(f);
	buf[got] = '\0';
	return buf;
}

int
smb_install(const char *text, enum smb_write *how)
{
	struct stat st;
	char *current;
	char *tmp;
	int displaced = 0;

	/* Never install a configuration that would leave the service unable to
	 * start (§9.5). This runs before anything is moved or preserved. */
	if (smb_validate(text) != 1)
		return -1;

	current = read_file(SMB_CONF);

	/* An identical result is not written at all. Changing the listening
	 * address needs a restart rather than a reload, and a restart drops
	 * connections clients may be using, so a needless write costs real
	 * work downstream (§9.5). */
	if (current && !strcmp(current, text)) {
		free(current);
		*how = SMB_WRITE_UNCHANGED;
		return 0;
	}

	/* The configuration in place before Graph first ran is preserved once,
	 * and never overwritten by a later run. Everything after the first is
	 * generated by Graph and reproducible from Graph's own inputs, so
	 * keeping copies of those would preserve nothing (§9.5). */
	if (current && stat(SMB_CONF_PRESERVED, &st) < 0 && errno == ENOENT) {
		if (!(tmp = write_temp("/etc/samba", current))) {
			free(current);
			return -1;
		}
		if (rename(tmp, SMB_CONF_PRESERVED) < 0) {
			unlink(tmp);
			free(tmp);
			free(current);
			return -1;
		}
		free(tmp);
		displaced = 1;
	}
	free(current);

	if (!(tmp = write_temp("/etc/samba", text)))
		return -1;
	if (chmod(tmp, 0644) < 0 || rename(tmp, SMB_CONF) < 0) {
		unlink(tmp);
		free(tmp);
		return -1;
	}
	free(tmp);

	*how = displaced ? SMB_WRITE_DISPLACED : SMB_WRITE_UPDATED;
	return 0;
}

/* Strips leading and trailing whitespace in place. */
static char *
trim(char *s)
{
	char *end;

	while (*s == ' ' || *s == '\t')
		s++;
	if (!*s)
		return s;
	end = s + strlen(s) - 1;
	while (end > s && (*end == ' ' || *end == '\t' || *end == '\r'))
		*end-- = '\0';
	return s;
}

/* Splits a Samba list value on whitespace into conf->addrs. */
static void
read_addrs(struct smb_conf *conf, char *value)
{
	char *tok, *save;

	for (tok = strtok_r(value, " \t", &save); tok;
	     tok = strtok_r(NULL, " \t", &save)) {
		if (conf->naddrs >= SMB_MAX_ADDRS)
			return;
		snprintf(conf->addrs[conf->naddrs], SMB_ADDR_MAX, "%s", tok);
		conf->naddrs++;
	}
}

int
smb_read(struct smb_conf *conf)
{
	struct smb_share *cur = NULL;
	char *text, *line, *save, *key, *value, *end;
	size_t i, kept;
	int global = 0;

	memset(conf, 0, sizeof(*conf));

	/* No configuration at all is not an error: it is what a first run
	 * finds, and there is simply nothing to carry forward. */
	if (!(text = read_file(SMB_CONF)))
		return 0;

	if (strncmp(text, SMB_HEADER, strlen(SMB_HEADER)) != 0) {
		free(text);
		return 0;
	}

	for (line = strtok_r(text, "\n", &save); line;
	     line = strtok_r(NULL, "\n", &save)) {
		line = trim(line);
		if (!*line || *line == '#' || *line == ';')
			continue;

		if (*line == '[') {
			if (!(end = strchr(line, ']')))
				continue;
			*end = '\0';
			line++;
			if (!strcasecmp(line, "global")) {
				global = 1;
				cur = NULL;
				continue;
			}
			global = 0;
			if (conf->nshares >= SMB_MAX_SHARES) {
				cur = NULL;
				continue;
			}
			cur = &conf->shares[conf->nshares++];
			snprintf(cur->name, SMB_NAME_MAX, "%s", line);
			continue;
		}

		if (!(value = strchr(line, '=')))
			continue;
		*value++ = '\0';
		key = trim(line);
		value = trim(value);

		if (global) {
			if (!strcasecmp(key, "interfaces"))
				read_addrs(conf, value);
			continue;
		}
		if (!cur)
			continue;
		if (!strcasecmp(key, "path"))
			snprintf(cur->path, PATH_MAX, "%s", value);
		else if (!strcasecmp(key, "valid users"))
			snprintf(cur->user, SMB_USER_MAX, "%s", value);
	}
	free(text);

	/* A section with no path defines nothing servable. Dropping it keeps a
	 * damaged file from producing a share pointing at nowhere. */
	for (i = 0, kept = 0; i < conf->nshares; i++) {
		if (!conf->shares[i].path[0])
			continue;
		if (kept != i)
			conf->shares[kept] = conf->shares[i];
		kept++;
	}
	conf->nshares = kept;

	return 1;
}

int
smb_restart(void)
{
	/* Debian and its derivatives call the unit smbd; others call it smb.
	 * Trying both is cheaper than identifying the distribution. */
	if (system("systemctl restart smbd >/dev/null 2>&1") == 0)
		return 0;
	if (system("systemctl restart smb >/dev/null 2>&1") == 0)
		return 0;
	return -1;
}

int
smb_on_linux(void)
{
#ifdef __linux__
	return 1;
#else
	return 0;
#endif
}

/* Appends addr to a comma-separated list in dst, if it fits. */
static void
list_add(char *dst, size_t size, const char *addr)
{
	size_t len = strlen(dst);

	if (len + strlen(addr) + 3 >= size)
		return;
	if (len)
		snprintf(dst + len, size - len, ", %s", addr);
	else
		snprintf(dst, size, "%s", addr);
}

/* Walks this machine's addresses, calling back with each as text. */
static int
each_address(void (*fn)(void *, const char *), void *ctx)
{
	struct ifaddrs *ifa, *p;
	char text[SMB_ADDR_MAX];
	const void *src;

	if (getifaddrs(&ifa) < 0)
		return -1;
	for (p = ifa; p; p = p->ifa_next) {
		if (!p->ifa_addr)
			continue;
		if (p->ifa_addr->sa_family == AF_INET)
			src = &((struct sockaddr_in *)(void *)
			    p->ifa_addr)->sin_addr;
		else if (p->ifa_addr->sa_family == AF_INET6)
			src = &((struct sockaddr_in6 *)(void *)
			    p->ifa_addr)->sin6_addr;
		else
			continue;
		if (!inet_ntop(p->ifa_addr->sa_family, src, text, sizeof(text)))
			continue;
		fn(ctx, text);
	}
	freeifaddrs(ifa);
	return 0;
}

struct match {
	const char *want;
	int found;
};

static void
match_one(void *ctx, const char *addr)
{
	struct match *m = ctx;

	/* An IPv6 address may carry a scope suffix; compare up to it. */
	if (!strncmp(addr, m->want, strcspn(addr, "%")) &&
	    strlen(m->want) == strcspn(addr, "%"))
		m->found = 1;
}

int
smb_local_address(const char *addr)
{
	struct match m;

	/* Every-interface is not an address of this machine and is not
	 * checked against one. */
	if (!strcmp(addr, SMB_ADDR_EVERY))
		return 1;

	m.want = addr;
	m.found = 0;
	if (each_address(match_one, &m) < 0)
		return -1;
	return m.found;
}

struct list {
	char *dst;
	size_t size;
};

static void
list_one(void *ctx, const char *addr)
{
	struct list *l = ctx;

	list_add(l->dst, l->size, addr);
}

int
smb_addresses(char *dst, size_t size)
{
	struct list l;

	if (size == 0)
		return -1;
	dst[0] = '\0';
	l.dst = dst;
	l.size = size;
	return each_address(list_one, &l);
}

int
smb_user_exists(const char *user)
{
	char cmd[SMB_USER_MAX + 64];

	/* Samba is asked directly rather than consulted through a record graph
	 * keeps: a user removed with smbpasswd -x must simply be seen to be
	 * gone the next time it matters (§10). */
	snprintf(cmd, sizeof(cmd), "pdbedit -L -u '%s' >/dev/null 2>&1", user);
	return system(cmd) == 0;
}

int
smb_user_create(const char *user, const char *password)
{
	char cmd[SMB_USER_MAX + 64];
	FILE *p;
	int rc;

	/* The password is written to smbpasswd's standard input. Passing it as
	 * an argument would put it in the process list for anyone on the
	 * machine to read (§10). */
	snprintf(cmd, sizeof(cmd), "smbpasswd -s -a '%s' >/dev/null 2>&1",
	    user);
	if (!(p = popen(cmd, "w")))
		return -1;
	fprintf(p, "%s\n%s\n", password, password);
	rc = pclose(p);
	return rc == 0 ? 0 : -1;
}

/* The VFS modules the generated share sections require. Without them a share
 * parses cleanly, is listed by the server, and then fails at connect time
 * with a message naming a Samba module rather than anything the operator
 * did. graph checks for them instead of letting that happen. */
static const char *vfs_modules[] = { "fruit", "streams_xattr" };

int
smb_vfs_modules(char *missing, size_t size)
{
	char dir[PATH_MAX] = "";
	char path[PATH_MAX];
	struct stat st;
	FILE *p;
	char line[512];
	size_t i;
	int absent = 0;

	if (size)
		missing[0] = '\0';

	/* smbd reports where its modules live; the directory is architecture
	 * and distribution specific, so it is asked for rather than guessed. */
	if (!(p = popen("smbd -b 2>/dev/null", "r")))
		return -1;
	while (fgets(line, sizeof(line), p)) {
		char *at = strstr(line, "MODULESDIR:");

		if (!at)
			continue;
		at += strlen("MODULESDIR:");
		while (*at == ' ' || *at == '\t')
			at++;
		at[strcspn(at, " \t\r\n")] = '\0';
		snprintf(dir, sizeof(dir), "%s", at);
		break;
	}
	pclose(p);

	if (!dir[0])
		return -1;

	for (i = 0; i < sizeof(vfs_modules) / sizeof(*vfs_modules); i++) {
		if (snprintf(path, sizeof(path), "%s/vfs/%s.so", dir,
		    vfs_modules[i]) >= (int)sizeof(path))
			continue;
		if (stat(path, &st) == 0)
			continue;
		absent++;
		if (size)
			list_add(missing, size, vfs_modules[i]);
	}
	return absent ? 0 : 1;
}

int
smb_stop(void)
{
	/* Stopping is left to systemd, which owns service state; graph only
	 * asks for it when nothing remains to serve (§2.4). */
	if (system("systemctl stop smbd >/dev/null 2>&1") == 0)
		return 0;
	if (system("systemctl stop smb >/dev/null 2>&1") == 0)
		return 0;
	return -1;
}

int
smb_name_ok(const char *s)
{
	size_t i;

	if (!*s)
		return 0;
	for (i = 0; s[i]; i++) {
		if ((s[i] >= 'a' && s[i] <= 'z') ||
		    (s[i] >= 'A' && s[i] <= 'Z') ||
		    (s[i] >= '0' && s[i] <= '9') ||
		    s[i] == '-' || s[i] == '_' || s[i] == '.')
			continue;
		return 0;
	}
	/* A leading dash would be read as an option by the commands graph
	 * runs, and a leading dot hides the share. */
	return s[0] != '-' && s[0] != '.';
}

int
smb_addr_ok(const char *s)
{
	size_t i;

	if (!*s)
		return 0;
	/* Graph does not interpret addresses (§9.3); this only keeps one from
	 * being read as an option or a shell fragment. */
	for (i = 0; s[i]; i++) {
		if ((s[i] >= '0' && s[i] <= '9') ||
		    (s[i] >= 'a' && s[i] <= 'f') ||
		    (s[i] >= 'A' && s[i] <= 'F') ||
		    s[i] == '.' || s[i] == ':')
			continue;
		return 0;
	}
	return s[0] != '-';
}

/* Runs a command directly, without a shell. Arguments therefore cannot be
 * split, globbed or reinterpreted, whatever a path or a share name contains.
 * Returns the exit status, or -1. */
int
smb_run(char *const argv[])
{
	pid_t pid;
	int status;

	if ((pid = fork()) < 0)
		return -1;
	if (pid == 0) {
		execvp(argv[0], argv);
		_exit(127);
	}
	while (waitpid(pid, &status, 0) < 0)
		if (errno != EINTR)
			return -1;
	if (WIFEXITED(status))
		return WEXITSTATUS(status);
	return -1;
}

int
smb_start(void)
{
	/* Starting is idempotent: a running service is left alone and no
	 * connection is dropped. That makes it safe to ask for whenever a
	 * repository should be served, without first working out whether the
	 * service happens to be up (§9.5 forbids needless restarts, not
	 * needless starts). */
	if (system("systemctl start smbd >/dev/null 2>&1") == 0)
		return 0;
	if (system("systemctl start smb >/dev/null 2>&1") == 0)
		return 0;
	return -1;
}

int
smb_running(void)
{
	/* Only whether the service is up is asked for, and only the exit
	 * status is used; systemctl's wording is not a contract. */
	if (system("systemctl is-active --quiet smbd >/dev/null 2>&1") == 0)
		return 1;
	if (system("systemctl is-active --quiet smb >/dev/null 2>&1") == 0)
		return 1;
	return 0;
}
